apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: camunda
  name: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: camunda
    spec: 
      securityContext: 
        runAsGroup: 1000 
        runAsUser:  1000
      containers:
      - image: camunda/camunda-bpm-platform:latest
        name: camunda 
        ports: 
        - containerPort: 8080
        env: 
          - name: USER_NAME
            valueFrom:
                secretKeyRef:
                   name: secret2   
                   key:  my-release-mysql
          






















































