apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-06-14T05:44:51Z"
  generateName: polling-app-mysql-
  labels:
    app: polling-app
    controller-revision-hash: polling-app-mysql-7c78b484c8
    statefulset.kubernetes.io/pod-name: polling-app-mysql-0
    tier: mysql
  name: polling-app-mysql-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: polling-app-mysql
    uid: 33d5b966-400c-4584-9ddd-df19619e0ce0
  resourceVersion: "282752"
  selfLink: /api/v1/namespaces/default/pods/polling-app-mysql-0
  uid: 68ae1d46-9ea0-4bcb-9e70-03ebdcc30a5a
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mysql-root-pass
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: mysql-user-pass
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mysql-user-pass
    image: mysql:5.6
    imagePullPolicy: IfNotPresent
    name: mysql
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-persistent-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7n786
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: polling-app-mysql-0
  nodeName: gke-williamhill-default-pool-7aa33d11-s61k
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: polling-app-mysql
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pv-claim
  - name: default-token-7n786
    secret:
      defaultMode: 420
      secretName: default-token-7n786
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-06-14T05:44:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-06-14T05:49:13Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-06-14T05:49:13Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-06-14T05:44:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://525d63b64efffd7a25fa108c0470a9618c2d0d7e4a9e72284851c321e30f8453
    image: docker.io/library/mysql:5.6
    imageID: docker.io/library/mysql@sha256:1d96ea86f9173607f1534c05041bf18dba691ded86d2ab51f6fd4533377fac39
    lastState: {}
    name: mysql
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-06-14T05:49:12Z"
  hostIP: 10.128.0.12
  phase: Running
  podIP: 10.100.0.12
  podIPs:
  - ip: 10.100.0.12
  qosClass: BestEffort
  startTime: "2021-06-14T05:44:51Z"
